# Generated by Django 5.0.2 on 2024-09-28 08:25

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_certificate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.utils.certificate_pictures_path),
        ),
    ]
