# Generated by Django 5.0.2 on 2024-10-02 03:48

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_certificate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(null=True, upload_to=accounts.utils.certificate_pictures_path),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image_hash',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
    ]
