# Generated by Django 5.0.2 on 2024-10-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_certificate_image_alter_certificate_image_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image_hash',
            field=models.CharField(default='', max_length=64),
        ),
    ]
